---
- name: "Gather Facts"
  hosts: lax-dc-tor-example1
  gather_facts: no
  
  tasks:
    - name: Gather Facts from IOS Devices
      ios_facts:
      
      register: output

    - name: Display facts variables
      debug:
        var: output

