---
- name: "Backup Running Configuration"
  hosts: lax-tor-r1
  gather_facts: no
  
  tasks:
    - name: 
      ios_config:
        backup: yes 
      when: ansible_network_os == 'ios'

    - name:
      nxos_config:
        backup: yes
      when: ansible_network_os == 'nxos'
      
